/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "main-bg": "#FAF9F6",
        dark: {
          DEFAULT: "#1B2432",
          primary: "#1B2432",
          secondary: "#2C2B3C",
          tertiary: "#403F4C",
        },
        light: {
          DEFAULT: "#EBE6E1",
          primary: "#CFC3BF",
          secondary: "#DFD9D4",
          tertiary: "#EBE6E1",
        },
        accent: {
          DEFAULT: "#F4663E",
          primary: "#F4663E",
          secondary: "#DA704A",
          tertiary: "#F57450",
          muted: "rgba(244, 102, 62, 0.08)",
        },
        academy: {
          deep: "#1f1f24",
          "deep-secondary": "#4a4d57",
          "deep-tertiary": "#737784",
          surface: "#f3f5f8",
          soft: "#e4e7ec",
          "soft-secondary": "#eff1f4",
          "soft-tertiary": "#f7f8fa",
        },
        body: "#2c3e50",
        muted: "#999",
        border: "#e0e0e0",
        "border-light": "#f0f0f0",
        success: "#22c55e",
        error: "#ef4444",
        warning: "#f59e0b",
      },
      fontFamily: {
        sans: ['"Helvetica Neue"', "Helvetica", "Arial", "sans-serif"],
        academy: ['"Avenir Next"', '"Nunito Sans"', '"Segoe UI"', "sans-serif"],
      },
      fontSize: {
        xs: ["0.9rem", { lineHeight: "1.2rem" }],
        sm: ["0.95rem", { lineHeight: "1.3rem" }],
        base: ["1rem", { lineHeight: "1.5rem" }],
        md: ["1.05rem", { lineHeight: "1.5rem" }],
        lg: ["1.2rem", { lineHeight: "1.7rem" }],
        xl: ["1.3rem", { lineHeight: "1.7rem" }],
        "2xl": ["1.5rem", { lineHeight: "1.9rem" }],
        "3xl": ["1.7rem", { lineHeight: "2.1rem" }],
        "4xl": ["1.9rem", { lineHeight: "2.3rem" }],
        "5xl": ["2.2rem", { lineHeight: "2.6rem" }],
        "6xl": ["2.6rem", { lineHeight: "3rem" }],
        "7xl": ["3rem", { lineHeight: "3.4rem" }],
      },
      maxWidth: {
        page: "1440px",
        content: "1280px",
        academy: "1280px",
        narrow: "1024px",
        form: "500px",
        auth: "450px",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(0, 0, 0, 0.04)",
        sm: "0 2px 4px rgba(0, 0, 0, 0.05)",
        md: "0 4px 12px rgba(0, 0, 0, 0.08)",
        lg: "0 8px 24px rgba(0, 0, 0, 0.12)",
        xl: "0 20px 60px rgba(0, 0, 0, 0.15)",
        glass: "0 8px 32px rgba(31, 38, 135, 0.37)",
        accent: "0 2px 8px rgba(244, 102, 62, 0.3)",
        "accent-hover": "0 4px 16px rgba(244, 102, 62, 0.4)",
        card: "0 4px 18px rgba(0, 0, 0, 0.03)",
        "card-hover": "0 8px 24px rgba(0, 0, 0, 0.08)",
      },
      borderRadius: {
        sm: "6px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "28px",
      },
      transitionDuration: {
        DEFAULT: "300ms",
        fast: "150ms",
        slow: "500ms",
      },
      transitionTimingFunction: {
        DEFAULT: "ease",
        smooth: "cubic-bezier(0.4, 0, 0.2, 1)",
      },
      backdropBlur: {
        glass: "16px",
      },
      keyframes: {
        "hero-reveal": {
          "0%": { opacity: "0", transform: "translateY(18px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "marquee-drift": {
          "0%": { transform: "translate3d(0, 0, 0)" },
          "100%": { transform: "translate3d(-50%, 0, 0)" },
        },
        "mesh-drift": {
          "0%": { transform: "translate3d(0, 0, 0) scale(1)" },
          "50%": { transform: "translate3d(2.5%, -2%, 0) scale(1.06)" },
          "100%": { transform: "translate3d(0, 0, 0) scale(1)" },
        },
        "nudge-float": {
          "0%": { transform: "translate3d(0, 0, 0)" },
          "50%": { transform: "translate3d(0, -8px, 0)" },
          "100%": { transform: "translate3d(0, 0, 0)" },
        },
        "beam-sweep-left": {
          "0%": { transform: "translate3d(0, 0, 0) rotate(16deg)" },
          "50%": { transform: "translate3d(56px, -20px, 0) rotate(20deg)" },
          "100%": { transform: "translate3d(0, 0, 0) rotate(16deg)" },
        },
        "beam-sweep-right": {
          "0%": { transform: "translate3d(0, 0, 0) rotate(-14deg)" },
          "50%": { transform: "translate3d(-62px, 18px, 0) rotate(-18deg)" },
          "100%": { transform: "translate3d(0, 0, 0) rotate(-14deg)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
      },
      animation: {
        "hero-reveal": "hero-reveal 0.8s ease-out both",
        "marquee-drift": "marquee-drift 30s linear infinite",
        "mesh-drift": "mesh-drift 22s ease-in-out infinite",
        "nudge-float": "nudge-float 6s ease-in-out infinite",
        "beam-sweep-left": "beam-sweep-left 18s ease-in-out infinite",
        "beam-sweep-right": "beam-sweep-right 20s ease-in-out infinite",
        "fade-in": "fade-in 0.4s ease-out both",
        "fade-in-up": "fade-in-up 0.5s ease-out both",
        "scale-in": "scale-in 0.3s ease-out both",
      },
    },
  },
  plugins: [],
};
